 HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: dev-krimple-shared-tasks
      ProtocolType: HTTP
  HttpApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: HttpApi
      StageName: "$default"
      AutoDeploy: true
  HttpApiAuthorizerSharedTasksJwtAuthorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      ApiId:
        Ref: HttpApi
      AuthorizerType: JWT
      IdentitySource:
      - "$request.header.Authorization"
      JwtConfiguration:
        Audience:
        - CognitoUserClientPoolId
        Issuer:
          Fn::Join:
          - ''
          - - https://cognito-idp.
            - us-east-1
            - ".amazonaws.com/"
            - CognitoIdentityPool
      Name: sharedTasksJwtAuthorizer

Outputs:
  HttpApiUrl:
    Description: URL of the HTTP API
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: HttpApi
        - ".execute-api."
        - Ref: AWS::Region
        - "."
        - Ref: AWS::URLSuffix
          HttpApi:
            Type: AWS::ApiGatewayV2::Api
            Properties:
              Name: dev-krimple-shared-tasks
              ProtocolType: HTTP
            HttpApiStage:
              Type: AWS::ApiGatewayV2::Stage
              Properties:
                ApiId:
                  Ref: HttpApi
                StageName: "$default"
                AutoDeploy: true
            HttpApiAuthorizerSharedTasksJwtAuthorizer:
              Type: AWS::ApiGatewayV2::Authorizer
              Properties:
                ApiId:
                  Ref: HttpApi
                AuthorizerType: JWT
                IdentitySource:
                  - "$request.header.Authorization"
                JwtConfiguration:
                  Audience:
                    - CognitoUserClientPoolId
                  Issuer:
                    Fn::Join:
                      - ''
                      - - https://cognito-idp.
                        - us-east-1
                        - ".amazonaws.com/"
                        - CognitoIdentityPool
                Name: sharedTasksJwtAuthorizer


      # - PolicyName: CognitoAuthorizedPolicy
      #   PolicyDocument:
      #     Version: '2012-10-17'
      #     Statement:
      #     - Effect: Allow
      #       Action:
      #       - mobileanalytics:PutEvents
      #       - cognito-sync:*
      #       - cognito-identity:*
      #       Resource: "*"
      #     - Effect: Allow
      #       Action:
      #       - execute-api:Invoke
      #       Resource:
      #         Fn::Join:
      #         - ''
      #         - - 'arn:aws:execute-api:'
      #           - Ref: AWS::Region
      #           - ":"
      #           - Ref: AWS::AccountId
      #           - ":"
      #           - httpApi
      #           - "/*"
 