AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31
Parameters:
  SharedTasksTableArn:
    Type: String
  StageName:
    Type: String
    Default: dev
  TaskManagerRoleName:
    Type: String

Resources:
  ManageTasksAddFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        def handler(event, context):
            import json
            return {
                "statusCode": 200,
                "body": json.dumps(event),
            }
      Handler: tasks-api/manage-tasks.add
      Runtime: python3.7
      Events:
        AddTaskEvent: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApiService
            Method: POST
            Path: /tasks
            TimeoutInMillis: 15000
            PayloadFormatVersion: "2.0"
            RouteSettings:
              ThrottlingBurstLimit: 600

  HttpApiService:
    Type: AWS::Serverless::HttpApi
    Properties:
      AccessLogSettings:
        DestinationArn: !GetAtt AccessLogs.Arn
        Format: $context.requestId
      StageName: !Ref StageName
      DefaultRouteSettings:
        DataTraceEnabled: True
        ThrottlingBurstLimit: 200
      RouteSettings:
        "POST /tasks":
          ThrottlingBurstLimit: 500
          LoggingLevel: ERROR

  AccessLogs:
    Type: AWS::Logs::LogGroup

  CognitoHttpMethodsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles: [ !Ref TaskManagerRoleName ]
      PolicyName: TaskTableDynamoPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:BatchGet*
              - dynamodb:DescribeTable
              - dynamodb:Get*
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:Delete*
              - dynamodb:Update*
              - dynamodb:PutItem
            Resource:
              Fn::Sub: "${SharedTasksTableArn}"

Outputs:
  HttpApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: 'https://${HttpApiService}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/'
  HttpApiId:
    Description: Api id of HttpApi
    Value:
      Ref: HttpApiService
